Add a patch for ceilometer to fit MOS9.2
In MOS9.2, it added a new function purge_inspection_cache() in
compute pollsters. Each pollsters' get_samples will invoke
self.inspector.purge_inspection_cache() firstly. But xenaip
doesn't define this function, so it will get the following error:
AttributeError: 'XenapiInspector' object has no attribute
'purge_inspection_cache'.
As this function doesn't exist in upstream, let's just apply a
patch to define a empty purge_inspection_cache(). So that it's
able to get samples successfully.

Change-Id: I1177c24651715566850c6fde67f74959b01c7e12