Exclude network.service.* polling meters
Currently we don't enable the vpn or lb service, so it will report
error: "Unable to discover resources: 404 Not Found". So let's add
them into the exclusion list.

Change-Id: I5922da6325fdde61be67c75068e0ce1a65d3e7da
(cherry picked from commit dc82f8f4826042d43d64fc7a605a7fc4b7471ef5)